name: pomodoro_timer
description: "simple pomodoro timer"
publish_to: "none"
version: 2.2.6+3

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^6.5.1
  file_picker: ^10.3.10
  shared_preferences: ^2.5.4
  permission_handler: ^12.0.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/notifications/
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
